# Site settings
title: GRAVITAL
description: > # this means to ignore newlines until "baseurl:"
repository: gravital-hr/gravital-hr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2019 - Start Bootstrap
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - vendor/bundle
  - LICENSE
  - README.md
